library:
  source-dirs: src
tests:
  gorilla-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - gorilla
copyright: 2018 Author name here
maintainer: example@example.com
dependencies:
  - base >= 4.7 && < 5
name: gorilla
version: 0.1.0.0
extra-source-files:
  - README.md
  - ChangeLog.md
author: Author name here
github: githubuser/gorilla
license: BSD3
executables:
  gorilla:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - turtle
      - gorilla
description: Please see the README on GitHub at <https://github.com/githubuser/gorilla#readme>
